# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Build & test on main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: "Build with Swift ${{ matrix.swift }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
        fail-fast: false
        matrix:
          os: [ubuntu-latest, macos-latest]
          swift: ["6.0", "5.10", "5.9", "5.8", "5.7.1"]

    steps:
    - uses: actions/checkout@v4
    - uses: NeedleInAJayStack/setup-swift@feat/swift-6 # TODO: Revert to swift-actions/setup-swift updates to support Swift 6.
      with:
        swift-version: ${{ matrix.swift }}
    - name: Build
      run: swift build -v
      
  test:
    name: "Run tests"
    runs-on: ubuntu-latest
    steps:
    - uses: NeedleInAJayStack/setup-swift@feat/swift-6 # TODO: Revert to swift-actions/setup-swift updates to support Swift 6.
      with:
        swift-version: "6.0"
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v --enable-code-coverage
